.PHONY: clean All

All:
	@echo "----------Building project:[ cwsw_evqueue - Debug ]----------"
	@"$(MAKE)" -f  "cwsw_evqueue.mk"
clean:
	@echo "----------Cleaning project:[ cwsw_evqueue - Debug ]----------"
	@"$(MAKE)" -f  "cwsw_evqueue.mk" clean
